language: python
python:
  - "3.5"

addons:
  apt:
    packages:
    - libleveldb-dev
    - libsqlite3-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - coverage run -m unittest discover neo
  - pycodestyle prompt.py
  - pycodestyle neo
  - pycodestyle examples
  - python prompt.py --version

after_success:
    coveralls

deploy:
  provider: pypi
  distributions: sdist
  user: CityOfZion
  password:
    secure: SECURE_PASSWORD_HERE
  on:
    tags: true
    all_branches: true
    repo: CityOfZion/neo-python
python: 3.5
